---
title: "Report_Phenology_GPIII"
author: "Dario Maccioni Vasquez"
date: "`r Sys.Date()`"
output: html_document
---


Search for all products in MODISTools and get the right one

```{r}
# load the library
library("MODISTools")

# list all available products
# (only showing first part of the table for brevity)
MODISTools::mt_products() |> 
  head()

View(mt_products())
```

Select from the chosen products the right bands, which are Greenup.Num_Modes_01 and Maturity.Num_Modes_01.

```{r}
# list bands for the MOD11A2
# product (a land surface temperature product)
MODISTools::mt_bands("MCD12Q2") |> 
  head()

View(mt_bands("MCD12Q2"))

```

Download Greenup Phenology

```{r}
# load libraries
library(MODISTools)

# download and save phenology data
Greenup <- MODISTools::mt_subset(
  product = "MCD12Q2",
  lat = 43.5,
  lon = 74.5,
  band = "Greenup.Num_Modes_01",
  start = "2001-01-01",
  end = "2009-12-31",
  km_lr = 100,
  km_ab = 100,
  site_name = "Adirondacks (North-Eastern United States)",
  internal = TRUE,
  progress = FALSE)

# print the dowloaded data
head(subset)
```


Search for bands in land cover product

```{r}
# list bands for the MOD11A2
# product (a land surface temperature product)
MODISTools::mt_bands("MCD12Q1") |> 
  head()

View(mt_bands("MCD12Q1"))

```


Nur IGBF Klassen herunerladen
```{r}
# load libraries
library(MODISTools)

# download and save phenology data
IGBP <- MODISTools::mt_subset(
  product = "MCD12Q1",
  lat = 43.5,
  lon = 74.5,
  band = "LC_Type1",
  start = "2010-01-01",
  end = "2010-12-31",
  km_lr = 100,
  km_ab = 100,
  site_name = "Adirondacks (North-Eastern United States)",
  internal = TRUE,
  progress = FALSE)

# print the dowloaded data
head(subset)
```

Aus Data Frame Daten filtern (NA werte)

```{r}

library(dplyr)
library(terra)
# screening of data
Greenup <- Greenup |>
  mutate(
    value = ifelse(value > 32656, NA, value),
    value = as.numeric(format(as.Date("2010-01-01") + value, "%j")),
    value = ifelse (value < 200, value, NA)
  )
```

Data Frame zu Raster

```{r}
Greenup_raster <- MODISTools::mt_to_terra(
  Greenup,
  reproject = TRUE
)
```

```{r}
install.packages("tidyterra")
```

```{r}
library(ggplot2)
library(terra)

ggplot() +
  tidyterra::geom_spatraster(data = Greenup_raster) +
  scale_fill_viridis_c(
    na.value = NA,
    name = "DOY"
    ) +
  theme_bw()
```

```{r}
library(terra)
library(ggplot2)
library(tidyterra)  # nach Installation laden

# Raster laden (nur wenn noch nicht passiert)
# Greenup_raster <- rast("pfad/zur/datei.tif")

ggplot() +
  tidyterra::geom_spatraster(data = Greenup_raster) +
  scale_fill_viridis_c(
    na.value = NA,
    name = "DOY"
  ) +
  theme_bw()

```

